on:
  push:
    branches:
      - main
jobs: 
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v1
      - run: yarn
      # - run: yarn test
      - name: Build Project
        run: yarn build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
            name: build
            path: './build'
  deploy-pages:
    runs-on: ubuntu-latest
    container: node:16
    needs: [build-node]
    steps: 
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Test artifact download  
        run: ls -R
      - name: Test artifact download
        run: ls -la
  build-netflify:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - uses: actions/checkout@v3
      - name: Build Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: S{{ secrets.NETLIFY_PER_TOKEN }}
        run: |
          yarn
          yarn buile-root
          npx netlify-cli deploy --dir=build --prod

  # checkChangesInDocs:
  #   name: Check changes in docs
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Check changes in stories
  #     uses: netlify/actions/diff-includes@master
  #     with:
  #       args: docs


